# Generated by Django 5.1.1 on 2024-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='propuesta',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='areas',
            field=models.ManyToManyField(to='propuestas.area'),
        ),
    ]
