# Generated by Django 5.1.1 on 2024-09-15 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='palabras_clave',
            field=models.ManyToManyField(to='propuestas.palabraclave'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='requisitos',
            field=models.ManyToManyField(to='propuestas.requisito'),
        ),
        migrations.AddIndex(
            model_name='propuesta',
            index=models.Index(fields=['nombre'], name='propuestas__nombre_81bcac_idx'),
        ),
        migrations.AddIndex(
            model_name='propuesta',
            index=models.Index(fields=['fecha_creacion'], name='propuestas__fecha_c_394c78_idx'),
        ),
    ]
