# Generated by Django 5.1.1 on 2024-09-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propuestas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
        ),
    ]
