# Generated by Django 5.1.1 on 2024-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='propuesta',
            name='tipo_propuesta',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuesta',
            name='datos_contacto',
            field=models.ManyToManyField(to='propuestas.datocontacto'),
        ),
    ]
