# Generated by Django 5.1.1 on 2024-10-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0002_area_propuesta_carrera_propuesta_areas'),
        ('propuestas', '0002_initial'),
    ]

    operations = [
    ]
