# Generated by Django 5.1.1 on 2024-11-01 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuestas', '0003_datocontacto_propuesta_tipo_propuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='propuesta',
            index=models.Index(fields=['visible'], name='propuestas__visible_b89e66_idx'),
        ),
    ]
