# Generated by Django 5.1.1 on 2024-10-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['user__email']},
        ),
        migrations.RemoveIndex(
            model_name='profesor',
            name='usuarios_pr_matricu_0e1d73_idx',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='matricula',
        ),
        migrations.AddField(
            model_name='alumno',
            name='areas_alumno',
            field=models.ManyToManyField(related_name='alumnos', to='usuarios.areaconocimiento'),
        ),
    ]
