# Generated by Django 5.1.1 on 2024-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_materia_remove_profesor_materias_profesor_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellido_materno',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='areas_profesor',
            field=models.ManyToManyField(related_name='profesores', to='usuarios.areaconocimiento'),
        ),
    ]
