# Generated by Django 5.1.1 on 2024-11-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_areaconocimiento_embedding_materia_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='primer_inicio',
            field=models.BooleanField(default=True),
        ),
    ]
