# Generated by Django 5.1.1 on 2024-11-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_customuser_is_admin'),
        ('usuarios', '0006_profesor_departamento_profesor_primer_inicio'),
    ]

    operations = [
    ]
