# Generated by Django 5.1.1 on 2024-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20241108_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='disponibilidad',
            field=models.IntegerField(default=5),
        ),
    ]
